### ISSUE TITLE
Правки по ЛР 3

### ISSUE THREAD

**Issue by BakasaRus** [DFirsa/ITMO_web_6sem#1]
Что заметил:

- [x] Города удаляются не всегда, а Петербург и какой-то Burlington International Airport так и не получилось удалить;
- [x] Стоит вынести логику всяких проверок в DAO;
- [x] Соединяться с БД при каждом запросе не очень хорошо, лучше сделать соединение один раз и потом его переиспользовать (и закрывать тоже один раз, при завершении приложения);
- [x] Express поддерживает [обработчики ошибок](https://expressjs.com/ru/guide/error-handling.html), стоит, наверно, воспользоваться ими, нежели ловить их самостоятельно;
- [x] [Вот тут](https://github.com/DFirsa/ITMO_web_6sem_server/blob/main/js/server.js#L37) лучше вынести логику в ApiRequester;
- [x] POST обычно возвращает 201 Created, если создаётся ресурс, а DELETE - 204 No Content, если удалённый ресурс не возвращается;
- [x] [Вот эту](https://github.com/DFirsa/ITMO_web_6sem_server/blob/main/js/apiRequester.js#L23) и соседнюю строчки нужно закинуть в одну, деструктурирующее присваивание такое может;
- [x] Лишние файлы лучше убрать;
- [x] `catch (error) { throw error; }` выглядит интересно.

Плюс было бы неплохо вынести сами контроллеры из скрипта, который запускает сервер

**Comment by DFirsa** [comment]
> * Стоит вынести логику всяких проверок в DAO;

Не очень понял что имеется ввиду, но в контроллерах оставил только проверки для параметров запроса

**Comment by BakasaRus** [comment]
> > * Стоит вынести логику всяких проверок в DAO;
> 
> Не очень понял что имеется ввиду, но в контроллерах оставил только проверки для параметров запроса

Наверно, да, это и имелось в виду

**Comment by BakasaRus** [comment]
Что ещё могу сказать:

- [x] `(async () => {await dao.connect()})();` - что за мем?) Почему нельзя просто `await dao.connect()`?
- [x] Наверно, стоит подключать вынесенные отдельно контроллеры через [эту штуку](https://expressjs.com/ru/guide/routing.html), в конце нужное;
- [ ] `return console.log()` выглядит мемно)) В целом, предполагалось, что будет заюзана какая-то функция, которая будет подключена через `app.use()` в конце, как в той доке по обработке ошибок.

**Comment by DFirsa** [comment]
> * [x]  `(async () => {await dao.connect()})();` - что за мем?) Почему нельзя просто `await dao.connect()`?

await не запускается вне async-функций, так что писал так, сейчас перенёс в app.listen

> * [ ]  `return console.log()` выглядит мемно)) В целом, предполагалось, что будет заюзана какая-то функция, которая будет подключена через `app.use()` в конце, как в той доке по обработке ошибок.

это чтобы если с самого начала если что-то сломалось, чтобы вывелась инфа, а так где try-cath были юзаю express-async-handler. [Вот например](https://github.com/DFirsa/ITMO_web_6sem_server/blob/main/routes/routes.js#L9)

**Comment by BakasaRus** [comment]
Тогда, наверно, лучше уж так:

```js
console.log();
return;
```
